### PR TITLE
Make serializer compat tests work again

### PR DESCRIPTION
**Pull request by andreasohlund**

### CODE REVIEW

**Comment by andreasohlund** [comment]
Seems like this has been broken for a while, all tests fails with

`OneTimeSetUp: SetUpAttribute attribute not allowed in a SetUpFixture` nunit 3 issue?

**Comment by andreasohlund** [comment]
@Particular/endtoend-maintainers ideas? seems like we need to stop using the OneTimeSetUp on the base fixture but that screwed up (I think) the cleanup. Perhaps separate base fixtures for the different tests "categories"?

**Comment by andreasohlund** [comment]
ping @Particular/endtoend-maintainers I need some help with this one. Would anyone be able to pair up?

**Comment by danielmarbach** [comment]
@andreasohlund made them work again except for the GenericMessage tests

**Comment by danielmarbach** [comment]
Green

**Comment by danielmarbach** [comment]
When this works we can add tests for the DateTime compatibility and potentially start fixing the generic message test

**Pull request merged**
