### PR TITLE
Adding SerializationCompatibilityTests from ProductionTests

### PR DESCRIPTION
**Pull request by hmemcpy**
This fixes https://github.com/Particular/ProductionTests/issues/50.
Tests have been updated to run with the latest NSB6.

We're streamlining the process of End-to-End testing, and moving existing tests from a private ProductionTests repo to here.
This PR moves the SerializationCompatTests.

### CODE REVIEW

**Comment by hmemcpy** [comment]
@Particular/nservicebus-maintainers please review and merge

**Comment by ramonsmits** [comment]
@hmemcpy What is this about? Why is this moved?

**Comment by ramonsmits** [comment]
If it is moved here, do you have a PR on the production tests that reflects the deletion of code there? Please add some links to the description too.

**Comment by hmemcpy** [comment]
@ramonsmits see linked issue. It's currently just a copy, the old code is still there. I will update the descriptions.

**Pull request merged**
