### PR TITLE
Sql server subscriptions

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/181

@SzymonPobiega @johnsimons 

This PR is based on top of #48

### CODE REVIEW

**Comment by danielmarbach** [comment]
I had to manipulate the message store to use a ConcurrentBag instead of a concurrent dictionary to actually verify that a can get multiple messages. I also had to hack a `Thread.Sleep` into it. There is an issue in how the subscriptions get tracked. I don't receive the subscriptions in the counter. Will investigate further tomorrow.

**Comment by danielmarbach** [comment]
Rebased

**Comment by SzymonPobiega** [comment]
Who has the power to merge this?

**Comment by danielmarbach** [comment]
I talked to @johnsimons and he said it is good to self-merge

**Pull request merged**
