### PR TITLE
[WIP] Nh saga compat testing more expressive tests

### PR DESCRIPTION
**Pull request by tmasternak**
Connects to Particular/PlatformDevelopment#737

### CODE REVIEW

**Comment by SimonCropp** [comment]
something is wrong with this PR. look at the commits and the diff

**Comment by tmasternak** [comment]
@SimonCropp forgot the `WIP`. In current form it's just spike to prove the idea. Thx for catching that!

**Comment by tmasternak** [comment]
This has been bundeled with #112. Closing

**Comment by SimonCropp** [comment]
@tmasternak delete branch?

**Comment by tmasternak** [comment]
@SimonCropp done - sorry for missing that.

**Pull request closed without merging**
