### PR TITLE
Make performance counters conditional

### PR DESCRIPTION
**Pull request by timbussmann**
@Particular/endtoend-maintainers performance counters are currently not supported on .net core (and if, only on windows) so I think we need to remove them from the performance tests altogether. It doesn't seem like these performance counters are actually read somewhere automatically, or did I miss something?

Maybe there are ways to configure alternative sinks we can log metrics to in the future, but that seems to be out of scope for now?

### CODE REVIEW

**Comment by ramonsmits** [comment]
Lets keep this in with a conditional compile.

**Comment by danielmarbach** [comment]
@ramonsmits why?

**Comment by ramonsmits** [comment]
@danielmarbach Because they are used during testing to get real-time feedback.

**Comment by timbussmann** [comment]
part of https://github.com/Particular/EndToEnd/pull/283 now

**Pull request closed without merging**
