### PR TITLE
Create performance test framework

### PR DESCRIPTION
**Pull request by WilliamBZA**
Connects to https://github.com/Particular/EndToEnd/issues/3

[Action plan](https://github.com/Particular/EndToEnd/blob/docs/docs/action-plan.md)

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/endtoend-maintainers can u please review this PR

**Comment by johnsimons** [comment]
It still marked as [WIP] ?

Also, has the the task force members done a code review yet ?

Can the description be updated with what this change is about and what is it for.

**Comment by WilliamBZA** [comment]
@johnsimons @SimonCropp this is very much still a WIP. We will request review and make sure all required descriptions are done once it is ready.

**Comment by johnsimons** [comment]
@WilliamBZA to be honest I am the only maintainer in this repo and since this is actually a new thing, I am not sure I can actually give you much feedback, I think the best bet IMO is for the taskforce members to review it and ensure it meets all the requirements. And feel free to use whatever code styles you guys prefer, I don't really care about that, I can always reformat it if I wish :wink:

**Comment by WilliamBZA** [comment]
This is ready to merge now. Ping @Particular/endtoend-maintainers 

_Note: Once this is merged the TeamCity build agent needs to be redirected to point to master instead of the `perf-tests` branch_

**Comment by hmemcpy** [comment]
Overall, looks good. I'm ok to merge this as-is, without additional squashing.

**Pull request merged**
