### PR TITLE
Testing saga get by correlation property

### PR DESCRIPTION
**Pull request by tmasternak**
Testing saga retrieval by `CorrelationProperty`.

### CODE REVIEW

**Comment by tmasternak** [comment]
ping @Particular/endtoend-maintainers

**Comment by SimonCropp** [comment]
shouldnt we instead disable lazy loading for the tests?

**Comment by tmasternak** [comment]
@SimonCropp good point. The reasons that I've put that in the first place where:
 * we could disable lazy-loading on the entity level but  `Persister` does not have any API to expose that
 * we could use the `ISatelessSession` instead of `ISession` but in v7 of `Persister` needs the latter  to do initialization

That being said I did a bit more research and found out that there is `NHibernateUtil.Initialize` method which does initialization for proxy object. Unfortunately it does not initialize child collections :/ so we can't use it in our scenario.

**Comment by tmasternak** [comment]
Closing this one. It has been merged into https://github.com/Particular/EndToEnd/pull/119

**Pull request closed without merging**
