### PR TITLE
Update and fix asq

### PR DESCRIPTION
**Pull request by melkio**
Connects to https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/86

### CODE REVIEW

**Comment by melkio** [comment]
@Particular/endtoend-maintainers ping

**Comment by johnsimons** [comment]
@melki since this is actually a new thing, I am not sure I can actually give you much feedback, I think the best bet IMO is for the taskforce members to review it and ensure it meets all the requirements. And feel free to use whatever code styles you guys prefer, I don't really care about that, I can always reformat it if I wish :wink:
Once you done, go ahead and merge it

**Comment by melkio** [comment]
@johnsimons are you referring to ASQ TF members?

**Comment by johnsimons** [comment]
> are you referring to ASQ TF members?

@melkio  Yes

**Comment by melkio** [comment]
@Particular/azure-storage-queues-maintainers: could you review this PR and then merge it, please?

**Comment by SeanFeldman** [comment]
Merged

**Pull request merged**
